repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios
repo_name: 2024.1-Correios
site_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios

site_name: Correios
nav: 
  - Equipe: "index.md"
  - Atas: 
    - Reunião 1: atas/ata1.md
    - Reunião 2: atas/ata2.md
    - Reunião 3: atas/ata3.md
    - Reunião 4: atas/ata4.md
  - Apresentações:
    - Apresentação 01: apresentações/apresentação-01.md
    - Apresentação 02: apresentações/apresentação-02.md
    - Apresentação 03: apresentações/apresentação-03.md
    - Apresentação 04: apresentações/apresentação-04.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/site_avaliados.md
    - Site Escolhido: planejamento/site-escolhido.md
    - Ferramentas do projeto: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo-design.md
  - Análise de Requisitos:
    - Aspectos Éticos: analise_de_requisitos/aspectos-eticos.md
    - Perfil de Usuário: analise_de_requisitos/perfil_de_usuario/perfil_de_usuario.md
    - Personas: analise_de_requisitos/personas.md
    - Cenários: analise_de_requisitos/cenarios.md
    - Análise de tarefas:
      - Análise Hierárquica de Tarefas: analise_de_requisitos/analise_tarefas/hta.md
      - CMN-GOMS: analise_de_requisitos/analise_tarefas/cmn_goms.md
  - Análise de Requisitos II:
    - Características da plataforma para o projeto: analise_de_requisitos2/caracteristicas-da-plataforma.md
    - Princípios Gerais: analise_de_requisitos2/principios_gerais.md
    - Metas de Usabilidade: analise_de_requisitos2/metas-usabilidade.md
    - Guia de Estilo: analise_de_requisitos2/guia_de_estilo.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento da Avaliação: design_avaliacao/nivel_1/analise_de_tarefas//planejamento-analise-tarefas.md
        - Planejamento do Relato dos Resultados: design_avaliacao/nivel_1/analise_de_tarefas/planejamento_relato_resultados_analise_de_tarefas.md
        - Relato dos Resultados:
          - Calcular Preços e Prazos: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/preco-prazos.md
          - Realizar Compras Online: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/loja-online.md
          - Recebimento de Encomendas: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/receber-encomenda.md
          - Realizar Pré-postagem: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/pre-postagem.md
          - Gerenciar Minhas Importações: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/gerenciar-importacoes.md
          - Rastrear Encomendas: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/rastrear-encomendas.md
      - Storyboard:
        - Planejamento da Avaliação: design_avaliacao/nivel_1/analise_dos_storyboards/planej_storyboard.md
        - Planejamento do Relato dos Resultados: design_avaliacao/nivel_1/analise_dos_storyboards/planejamento-relato-storyboard.md
        - Relato dos Resultados:
          - Calcular Preços e Prazos: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_calculo_de_preços.md
          - Realizar Compras Online: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_loja_online.md
          - Recebimento de Encomendas: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_receber_encomendas.md
          - Realizar Pré-postagem: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_pre_postagem.md
          - Gerenciar Minhas Importações: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_minhas_importacoes.md
          - Rastrear Encomendas: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_rastreamento_encomendas.md
        - Storyboards: design_avaliacao/storyboards.md
    - Nível 2:
      - Protótipo de Papel:
        - Planejamento da Avaliação: design_avaliacao/nivel_2/prototipo_de_papel/planejamento_avaliacao.md
        - Planejamento do Relato dos Resultados: design_avaliacao/nivel_2/prototipo_de_papel/planejamento_relato_resultados.md
extra_css:
  - stylesheets/extra.css
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios-icon-black.svg
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme : default
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo escuro 

    - scheme: slate
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o modo claro

