repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios
repo_name: 2024.1-Correios
site_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios

site_name: Correios
nav: 
  - Equipe: "index.md"
  - Atas: 
    - Reunião 1: atas/ata1.md
    - Reunião 2: atas/ata2.md
    - Reunião 3: atas/ata3.md
    - Reunião 4: atas/ata4.md
    - Reunião 5: atas/ata5.md
    - Reunião 6: atas/ata6.md
  - Apresentações:
    - Apresentação 01: apresentações/apresentação-01.md
    - Apresentação 02: apresentações/apresentação-02.md
    - Apresentação 03: apresentações/apresentação-03.md
    - Apresentação 04: apresentações/apresentação-04.md
    - Apresentação 05: apresentações/apresentação-05.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/site_avaliados.md
    - Site Escolhido: planejamento/site-escolhido.md
    - Ferramentas do projeto: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo-design.md
  - Análise de Requisitos:
    - Aspectos Éticos: analise_de_requisitos/aspectos-eticos.md
    - Perfil de Usuário: analise_de_requisitos/perfil_de_usuario/perfil_de_usuario.md
    - Personas: analise_de_requisitos/personas.md
    - Cenários: analise_de_requisitos/cenarios.md
    - Análise de tarefas:
      - Análise Hierárquica de Tarefas: analise_de_requisitos/analise_tarefas/hta.md
      - CMN-GOMS: analise_de_requisitos/analise_tarefas/cmn_goms.md
  - Análise de Requisitos II:
    - Características da plataforma para o projeto: analise_de_requisitos2/caracteristicas-da-plataforma.md
    - Princípios Gerais: analise_de_requisitos2/principios_gerais.md
    - Metas de Usabilidade: analise_de_requisitos2/metas-usabilidade.md
    - Guia de Estilo: analise_de_requisitos2/guia_de_estilo.md
  - Design, Avaliação e Desenvolvimento:
    - Nível 1:
      - Análise de Tarefas:
        - Planejamento da Avaliação: design_avaliacao/nivel_1/analise_de_tarefas//planejamento-analise-tarefas.md
        - Planejamento do Relato dos Resultados: design_avaliacao/nivel_1/analise_de_tarefas/planejamento_relato_resultados_analise_de_tarefas.md
        - Relato dos Resultados:
          - Calcular Preços e Prazos: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/preco-prazos.md
          - Realizar Compras Online: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/loja-online.md
          - Recebimento de Encomendas: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/receber-encomenda.md
          - Realizar Pré-postagem: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/pre-postagem.md
          - Gerenciar Minhas Importações: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/gerenciar-importacoes.md
          - Rastrear Encomendas: design_avaliacao/nivel_1/analise_de_tarefas/relato-resultados/rastrear-encomendas.md
      - Storyboard:
        - Planejamento da Avaliação: design_avaliacao/nivel_1/analise_dos_storyboards/planej_storyboard.md
        - Planejamento do Relato dos Resultados: design_avaliacao/nivel_1/analise_dos_storyboards/planejamento-relato-storyboard.md
        - Relato dos Resultados:
          - Calcular Preços e Prazos: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_calculo_de_preços.md
          - Realizar Compras Online: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_loja_online.md
          - Recebimento de Encomendas: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_receber_encomendas.md
          - Realizar Pré-postagem: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_pre_postagem.md
          - Gerenciar Minhas Importações: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_minhas_importacoes.md
          - Rastrear Encomendas: design_avaliacao/nivel_1/analise_dos_storyboards/Relatos_StoryBoards/Relato_rastreamento_encomendas.md
        - Storyboards: design_avaliacao/storyboards.md
    - Nível 2:
      - Protótipo de Papel:
        - Planejamento da Avaliação: design_avaliacao/nivel_2/prototipo_de_papel/planejamento_avaliacao.md
        - Planejamento do Relato dos Resultados: design_avaliacao/nivel_2/prototipo_de_papel/planejamento_relato_resultados.md
  - Verificação:
    - Grupo 4:
      - Planejamento:
        - Planejamento da verificação: verificacao_01/grupo_04/planejamento/Planejamento.md
        - Metodologia: planejamento/metodologia.md
        - Cronograma: planejamento/cronograma.md
        - Cronograma Executado: planejamento/cronograma_executado.md
        - Heatmap: planejamento/heatmap.md
        - Sites Avaliados: planejamento/sitesAvaliados.md
        - Ferramentas: verificacao_01/grupo_04/planejamento/ferramentas.md
        - Processos Design: planejamento/processoDesign.md
        - Site Escolhido: planejamento/siteescolhido.md
      - Análise de Requisitos I:
        - Aspectos Éticos: analise_requisitos1/aspectos_éticos.md
        - Perfil do Usuário:
            - Questionário : analise_requisitos1/perfil_do_usuario/questionario.md
            - Entrevista: analise_requisitos1/perfil_do_usuario/questionariopr.md
            - Análise Competitiva: analise_requisitos1/perfil_do_usuario/analise_competitiva.md
            - Resultado do Perfil do Usuário: analise_requisitos1/perfil_do_usuario/resultado.md
        - Personas: analise_requisitos1/personas.md
        - Cenários : analise_requisitos1/cenario.md
        - Análise de tarefas:
            - HTA: analise_requisitos1/analise_tarefas/hta.md
            - GOMS: analise_requisitos1/analise_tarefas/goms.md
      - Análise de Requisitos II:
        - Princípios Gerais do Projeto: analise_requisitos2/principios_gerais.md
        - Metas de Usabilidade: analise_requisitos2/metas_usabilidade.md
        - Guia de Estilo: analise_requisitos2/guia_estilo.md
        - Características da plataforma: analise_requisitos2/caracteristicos.md
      - Design, Avaliação e Desenvolvimento :
        - Nivel 1:
          - Análise de tarefas:
            - Planejamento da Avaliação da Análise de Tarefas : design/Nivel1/analise_tarefas/planejamento_avaliação.md
            - Planejamento do Relato dos Resultados da Avaliação: design/Nivel1/analise_tarefas/planejamento_relato.md
            - Relato dos Resultados: design/Nivel1/analise_tarefas/relato.md
          - Storyboard:
            - Planejamento da Avaliação do Storyboard : design/Nivel1/storyboard/planejamento_avaliação.md
            - Planejamento do Relato dos Resultados da Avaliação: design/Nivel1/storyboard/planejamento_relato.md
            - Relato dos Resultados: design/Nivel1/storyboard/relato.md
            - Storyboards: design/Nivel1/storyboard/storyboard.md
        - Nivel 2:
          - Protótipo de Papel:
            - Planejamento da Avaliação do Protótipo de Papel : design/Nivel2/prototipo_papel/planejamento_avaliação.md
            - Planejamento do Relato do Protótipo de Papel: design/Nivel2/prototipo_papel/planejamento_relato.md
extra_css:
  - stylesheets/extra.css
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios-icon-black.svg
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme : default
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo escuro 

    - scheme: slate
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o modo claro

