repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios
repo_name: 2024.1-Correios
site_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios

site_name: Correios
nav: 
  - Equipe: "index.md"
  - Atas: 
    - Reunião 1: atas/ata1.md
    - Reunião 2: atas/ata2.md
    - Reunião 3: atas/ata3.md
    - Reunião 4: atas/ata4.md
  - Apresentações:
    - Apresentação 01: apresentações/apresentação-01.md
    - Apresentação 02: apresentações/apresentação-02.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/site_avaliados.md
    - Site Escolhido: planejamento/site-escolhido.md
    - Ferramentas do projeto: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo-design.md
  - Análise de Requisitos:
    - Aspectos Éticos: analise_de_requisitos/aspectos-eticos.md
    - Perfil de Usuário: analise_de_requisitos/perfil_de_usuario/perfil_de_usuario.md
    - Personas: analise_de_requisitos/personas.md
    - Cenários: analise_de_requisitos/cenarios.md
    - Análise de tarefas:
      - Análise Hierárquica de Tarefas: analise_de_requisitos/analise_tarefas/hta.md
      - CMN-GOMS: analise_de_requisitos/analise_tarefas/cmn_goms.md
extra_css:
  - stylesheets/extra.css
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios-icon-black.svg
  features:
    - navigation.tabs
    - navigation.top
  palette:
    - scheme : default
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch
        name: Mudar para o modo escuro 

    - scheme: slate
      primary: amber
      accent: custom
      toggle:
        icon: material/toggle-switch-off-outline
        name: Mudar para o modo claro

