repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Grupo03
repo_name: 2024.1-Grupo_03
site_url: https://github.com/Interacao-Humano-Computador/2024.1-Grupo03

site_name: Correios
nav: 
  - Inicio: "index.md"
  - Atas: 
    - Ata1: "atas/ata1.md"
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
      - Sites Avaliados: planejamento/site_avaliados.md
      - Processo de Design: planejamento/processo-design.md
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios_icon.svg
  features:
    - navigation.tabs
  palette:

    # Palette toggle for light mode
    
    - scheme: default
      primary: orange
      toggle:
        icon: material/lightbulb
        name: Mudar para o modo escuro

    # Palette toggle for dark mode
        
    - scheme: slate
      primary: teal
      toggle:
        icon: material/lightbulb
        name: Mudar para o modo claro
