repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Grupo03
repo_name: 2024.1-Grupo_03
site_url: https://github.com/Interacao-Humano-Computador/2024.1-Grupo03

site_name: Correios
nav: 
  - Inicio: "index.md"
  - Atas: 
    - Ata1: "atas/ata1.md"
  - Apresentações:
      - Apresentação 01: apresentações/apresentação-01.md
  - Planejamento:
      - Heatmap: planejamento/heatmap.md
      - Sites Avaliados: planejamento/site_avaliados.md
      - Processo de Design: planejamento/processo-design.md
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios.svg
  features:
    - navigation.tabs
  palette:
  
    - scheme: default
      primary: amber
      toggle:
        icon: material/eye
        name: Mudar para o modo escuro

    - scheme: slate
      primary: blue
      toggle:
        icon: material/eye-outline
        name: Mudar para o modo claro
