repo_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios
repo_name: 2024.1-Correios
site_url: https://github.com/Interacao-Humano-Computador/2024.1-Correios

site_name: Correios
nav: 
  - Equipe: "index.md"
  - Atas: 
    - Ata1: "atas/ata1.md"
    - Ata2: "atas/ata2.md"
    - Ata3: "atas/ata3.md"
  - Apresentações:
    - Apresentação 01: apresentações/apresentação-01.md
  - Planejamento:
    - Heatmap: planejamento/heatmap.md
    - Sites Avaliados: planejamento/site_avaliados.md
    - Site Escolhido: planejamento/site-escolhido.md
    - Ferramentas do projeto: planejamento/ferramentas.md
    - Cronograma: planejamento/cronograma.md
    - Processo de Design: planejamento/processo-design.md
  - Análise de Requisitos:
    - Perfil de Usuário: analise_de_requisitos/perfil_de_usuario/perfil_de_usuario.md
    - Análise de tarefas:
      - Análise Hierárquica: analise_de_requisitos\analise_de_tarefas\hta.md
      - CMN-GOMS: analise_de_requisitos/analise_de_tarefas/cmn_goms.md
extra_css:
  - stylesheets/extra.css
theme:
  language: pt-BR
  name: material
  favicon: assets/correios_icon.svg
  logo: assets/correios.svg
  features:
    - navigation.tabs
  palette:
  
    - scheme: default
      primary: amber
      toggle:
        icon: material/eye
        name: Mudar para o modo escuro

    - scheme: slate
      primary: blue
      toggle:
        icon: material/eye-outline
        name: Mudar para o modo claro
